### PR TITLE
fix-negative-Int-rendered-as-left-arrow

### PR DESCRIPTION
**Pull request by NoSloppy**

### CODE REVIEW

**Comment by profezzorn** [comment]
What browser renders <- as a "left arrow" ?

**Comment by NoSloppy** [comment]
> What browser renders <- as a "left arrow" ?

Google Chrome Version 108.0.5359.124 (Official Build) (x86_64)
Screen Shot 2023-01-12 at 4 35 25 AM

**Comment by profezzorn** [comment]
Weird, my chrome isn't doing that.
Is this on Mac by any chance? (macs are weird)

**Comment by NoSloppy** [comment]
Yes Mac.

**Comment by profezzorn** [comment]
My chrome@mac is NOT doing this though.
Do you have a plugin or something?
Or is your style editor deployed somewhere that does post-processing?

**Comment by NoSloppy** [comment]
I mean, yes I have plugins for like smooth scrolling and I've set flags to use dark mode, but nothing font related.
Bottom line, if it's just me I'll just keep a local version that puts a space there and we can disregard this PR if it is not helping the masses.

**Comment by NoSloppy** [comment]
> My chrome@mac is NOT doing this though. Do you have a plugin or something? Or is your style editor deployed somewhere that does post-processing?

Maybe some css style sheet or something is different?
Safari doesn't do it.
Chrome in my VM Windows doesn't.
I don't know where to look.
and ultimately, there are much more pertinent things to spend time on.

**Comment by profezzorn** [comment]
I thought I'd be able to google what's doing it, but no such luck so far...
For now I'm going to close this. If this turns out to be a more widespread problem, we'll revisit.

**Pull request closed without merging**
