### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by NoSloppy**

### CODE REVIEW

**Comment by NoSloppy** [comment]
it was this:
make-favicon

**Comment by profezzorn** [comment]
I wonder if we could make the image slightly more identifiable by cropping it more.  Just do a "zoom and enhance" on the left 20% of the picture or something?

**Comment by NoSloppy** [comment]
It seems to work leaving the resolution higher than 16x16. How the update look?
SE_Favicon

**Comment by NoSloppy** [comment]
or.... how about something like this?
Screenshot 2023-06-30 at 8 43 43 PM

**Comment by profezzorn** [comment]
I think I like the image better than the ascii, although the image needs to be square.
I haven't tried scaling it down to 16x16 to see what that looks like though.

Oh, and when you re-crop the image, maybe put the bunny ears in the center?

**Comment by NoSloppy** [comment]
It's a fine line of cropping out the handle for recognition...but it's so small I don't think it's going to matter.
How about this:
SE_Favicon
0d6e7)

**Comment by profezzorn** [comment]
Well, let's try it and see...

**Pull request merged**
