### PR TITLE
Variant Slider and some styling

### PR DESCRIPTION
**Pull request by NoSloppy**

### CODE REVIEW

**Comment by NoSloppy** [comment]
hold on. need to make direct input update things.

**Comment by NoSloppy** [comment]
ok, now clicking and holding arrows increases speed of change of variant value. 
Slider and value box stay in sync.

**Comment by profezzorn** [comment]
What does this actually look like?

**Comment by NoSloppy** [comment]
> 

https://www.dropbox.com/s/ijdj3nccvvirh96/style_editor.html?dl=0

**Pull request merged**
